'use client'
import {useEffect,useState} from 'react'
import {api} from '../../lib/api'

type B=any
export default function Dashboard(){const [me,setMe]=useState<any>(null),[rows,setRows]=useState<B[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[newPass,setNewPass]=useState(''),[selected,setSelected]=useState<B|null>(null),[tests,setTests]=useState('')
 const load=async()=>{try{const m=await api<any>('/me');setMe(m);const x=await api<any>('/my/bookings');setRows(x.bookings||[])}catch(e:any){setMsg(e.message);if(e.message==='Unauthorized')location.href='/login'}}
 useEffect(()=>{if(localStorage.getItem('mtb_user_token'))load();else location.href='/login'},[])
 async function status(ref:string,status:string){try{setBusy(true);await api(`/bookings/${encodeURIComponent(ref)}/status`,{method:'POST',body:JSON.stringify({status})});await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function savePassword(){try{await api('/change-password',{method:'POST',body:JSON.stringify({new_password:newPass})});setNewPass('');setMsg('Password changed.')}catch(e:any){setMsg(e.message)}}
 async function addExtras(){if(!selected)return;const codes=tests.split(',').map(x=>x.trim()).filter(Boolean).map(code=>({code}));try{setBusy(true);await api(`/bookings/${encodeURIComponent(selected.reference)}/extra-tests`,{method:'POST',body:JSON.stringify({tests:codes})});setTests('');setMsg('Extra tests added.');await load();const x=await api<any>(`/bookings/${encodeURIComponent(selected.reference)}`);setSelected({...x.booking,extra_tests:x.extra_tests})}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 if(!me)return <main className="p-6">Loading…</main>;const p=me.user?.permissions||[];return <main className="min-h-screen bg-slate-50 p-4"><div className="mx-auto max-w-6xl"><header className="rounded-2xl bg-slate-900 p-6 text-white"><div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-2xl font-bold">{me.user.display_name}</h1><p className="mt-1 text-sm text-slate-300">{me.user.user_type}</p></div><button onClick={()=>{localStorage.removeItem('mtb_user_token');location.href='/login'}} className="rounded-lg border border-white/20 px-3 py-2">Logout</button></div></header>{msg&&<div className="mt-4 rounded-xl border bg-white p-3 text-sm">{msg}</div>}
 <section className="mt-5 rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-bold">My / Assigned Reservations</h2><p className="text-sm text-slate-500">Status and actions are enforced by your permissions.</p></div><button onClick={load} className="rounded-lg border px-3 py-2">Refresh</button></div><div className="mt-4 grid gap-3">{rows.map(b=><article key={b.reference} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><div dir="auto" className="font-bold">{b.patient_name}</div><div className="text-sm text-slate-500">{b.reference} · {b.phone} · {b.total} EGP</div><div className="mt-1 text-sm">Status: <b>{b.status}</b>{b.assigned_name&&` · Assigned: ${b.assigned_name}`}</div></div><button onClick={async()=>{const x=await api<any>(`/bookings/${encodeURIComponent(b.reference)}`);setSelected({...x.booking,extra_tests:x.extra_tests})}} className="rounded-lg bg-slate-900 px-3 py-2 text-sm text-white">Details</button></div><div className="mt-3 flex flex-wrap gap-2">{b.status==='ASSIGNED'&&p.includes('accept_assigned_reservations')&&<button disabled={busy} onClick={()=>status(b.reference,'ACCEPTED')} className="rounded-lg bg-slate-900 px-3 py-2 text-sm text-white">Accept Reservation</button>}{b.status==='ACCEPTED'&&p.includes('confirm_visits')&&<button disabled={busy} onClick={()=>status(b.reference,'CONFIRMED')} className="rounded-lg bg-slate-900 px-3 py-2 text-sm text-white">Confirm Visit</button>}{b.status==='CONFIRMED'&&p.includes('mark_visits_done')&&<button disabled={busy} onClick={()=>status(b.reference,'DONE')} className="rounded-lg bg-slate-900 px-3 py-2 text-sm text-white">Mark Visit Done</button>}{b.status==='CONFIRMED'&&p.includes('edit_confirmed_assigned_reservations')&&<button onClick={()=>setSelected(b)} className="rounded-lg border px-3 py-2 text-sm">Edit confirmed reservation</button>}</div></article>)}{!rows.length&&<p className="py-8 text-center text-slate-500">No reservations.</p>}</div></section>
 <section className="mt-5 rounded-2xl border bg-white p-5"><h2 className="font-bold">Change Password</h2><div className="mt-3 flex gap-2"><input type="password" value={newPass} onChange={e=>setNewPass(e.target.value)} placeholder="New password" className="flex-1 rounded-lg border px-3 py-2"/><button onClick={savePassword} disabled={!newPass} className="rounded-lg bg-slate-900 px-4 py-2 text-white disabled:opacity-40">Save</button></div></section>
 {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-xl overflow-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">{selected.reference}</h2><button onClick={()=>setSelected(null)}>✕</button></div><div className="mt-4 grid gap-2 text-sm"><div>Patient: <b dir="auto">{selected.patient_name}</b></div><div>Phone: {selected.phone}</div><div>Status: <b>{selected.status}</b></div><div>Total: <b>{selected.total} EGP</b></div></div>{selected.status==='CONFIRMED'&&p.includes('add_extra_tests')&&<div className="mt-5 rounded-xl bg-slate-50 p-4"><h3 className="font-bold">Add extra tests</h3><p className="mt-1 text-xs text-slate-500">Enter test numbers separated by commas. Each new test earns the configured extra-test commission.</p><input value={tests} onChange={e=>setTests(e.target.value)} placeholder="e.g. 101, 230" className="mt-3 w-full rounded-lg border px-3 py-2"/><button disabled={busy||!tests.trim()} onClick={addExtras} className="mt-2 rounded-lg bg-slate-900 px-4 py-2 text-white">Add tests</button></div>}<div className="mt-5 flex justify-end"><button onClick={()=>setSelected(null)} className="rounded-lg border px-4 py-2">Close</button></div></div></div>}</div></main>}
